return enum("Dox.SYNTAX",
{
"ADA",
"ASSEMBLY_NASM",
"C",
"C_SHARP",
"C_PLUS_PLUS",
"CSS",
"DART",
"ELM",
"F_SHARP",
"FORTRAN",
"GO",
"GROOVY",
"HASKELL",
"HTML",
"JAVA",
"JAVASCRIPT",
"JULIA",
"KOTLIN",
"LUA",
"MATLAB",
"OBJECTIVE_C",
"PERL",
"PHP",
"PYTHON",
"RUBY",
"RUST",
"SCALA",
"SWIFT",
"TYPESCRIPT",
"XML"
},
{
DoxSyntax("Ada",                  "--",       "--",       "\\"),
DoxSyntax("Assembly (NASM)",      "%{",       "%}",       "\\"),
DoxSyntax("C",                    "/*",       "*/",       "\\"),
DoxSyntax("C#",                   "/*",       "*/",       "\\"),
DoxSyntax("C++",                  "/*",       "*/",       "\\"),
DoxSyntax("CSS",                  "/*",       "*/",       "\\"),
DoxSyntax("Dart",                 "/*",       "*/",       "\\"),
DoxSyntax("Elm",                  "{-",       "-}",       "\\"),
DoxSyntax("F#",                   "(*",       "*)",       "\\"),
DoxSyntax("Fortran",              "!",        "\\n",      "\\"),
DoxSyntax("Go",                   "/*",       "*/",       "\\"),
DoxSyntax("Groovy",               "/*",       "*/",       "\\"),
DoxSyntax("Haskell",              "{-",       "-}",       "\\"),
DoxSyntax("HTML",                 "<!--",     "-->",      "\\"),
DoxSyntax("Java",                 "/*",       "*/",       "\\"),
DoxSyntax("JavaScript",           "/*",       "*/",       "\\"),
DoxSyntax("Julia",                "#=",       "=#",       "\\"),
DoxSyntax("Kotlin",               "/*",       "*/",       "\\"),
DoxSyntax("Lua",                  "--[[",     "]]",       "\\"),
DoxSyntax("Matlab",               "%{",       "%}",       "\\"),
DoxSyntax("Objective-C",          "/*",       "*/",       "\\"),
DoxSyntax("Perl",                 "=pod",     "=cut",     "\\"),
DoxSyntax("PHP",                  "/*",       "*/",       "\\"),
DoxSyntax("Python",               '"""',      '"""',      "\\"),
DoxSyntax("Ruby",                 "=begin",   "=end",     "\\"),
DoxSyntax("Rust",                 "/*",       "*/",       "\\"),
DoxSyntax("Scala",                "/*",       "*/",       "\\"),
DoxSyntax("Swift",                "/*",       "*/",       "\\"),
DoxSyntax("TypeScript",           "/*",       "*/",       "\\"),
DoxSyntax("XML",                  "<!--",     "-->",      "\\"),
},
true);
